
import { Router } from 'express';
import { searchAllEntities } from '../controllers/search.controller';
import userRouter from './user.routes';
import { aiModelRoutes } from './aiModel.routes';
import aiPlatformRouter from './aiPlatform.routes';
import aiKeyRouter from './aiKey.routes';
import billingRouter from './billing.routes';
import roleRouter from './role.routes';
import permissionRouter from './permission.routes';
import { router as tokenRouter } from './token.routes';
import notificationTemplateRouter from './notificationTemplate.routes';
import notificationRouter from './notification.routes';
import mailTemplateRouter from './mailTemplate.routes';
import mailRouter from './mail.routes';
import ssoRouter from './sso.routes';
import loginHistoryRouter from './loginHistory.routes';
import logicHistoryRouter from './logicHistory.routes';
import cacheRouter from './cache.routes';
import apiKeyRouter from './apiKey.routes';
import agentRouter from './agent.routes';
import conversationRouter from './conversation.routes';
import labelRouter from './label.routes';
import seedRouter from './seed.routes';
import loggerRouter from './logger.routes';
import databaseConnectionRouter from './database-connection.routes';
import socketRoutes from './socket.routes';
import documentRouter from './document.routes';
import faqRouter from './faq.routes';
import uiConfigRouter from './uiconfig.routes';
import jobRouter from './job.routes';
import memoryRouter from './memory.routes';
import toolRouter from './tool.routes';
import systemRouter from './system.routes';
import commandRouter from './command.routes';
import fileRouter from './file.routes';
import promptHistoryRouter from './promptHistory.routes';
import { entityRoutes } from './entity.routes';
import { entityMethodRoutes } from './entity_method.routes';
import { entityMethodRouter } from './entitymethod.routes';

const router = Router();

router.use('/users', userRouter);
router.use('/ai-models', aiModelRoutes);
router.use('/ai-platforms', aiPlatformRouter);
router.use('/ai-keys', aiKeyRouter);
router.use('/billings', billingRouter);
router.use('/roles', roleRouter);
router.use('/permissions', permissionRouter);
router.use('/tokens', tokenRouter);
router.use('/notification-templates', notificationTemplateRouter);
router.use('/notifications', notificationRouter);
router.use('/mail-templates', mailTemplateRouter);
router.use('/mails', mailRouter);
router.use('/sso', ssoRouter);
router.use('/login-history', loginHistoryRouter);
router.use('/logic-history', logicHistoryRouter);
router.use('/cache', cacheRouter);
router.use('/api-keys', apiKeyRouter);
router.use('/agents', agentRouter);
router.use('/conversations', conversationRouter);
router.use('/labels', labelRouter);
router.use('/seed', seedRouter);
router.use('/logs', loggerRouter);
router.use('/database-connections', databaseConnectionRouter);
router.use('/sockets', socketRoutes);
router.use('/documents', documentRouter);
router.use('/faqs', faqRouter);
router.use('/ui-config', uiConfigRouter);
router.use('/jobs', jobRouter);
router.use('/memories', memoryRouter);
router.use('/tools', toolRouter);
router.get('/search', searchAllEntities);
router.use('/system', systemRouter);
router.use('/tool-commands', commandRouter);

router.use('/files', fileRouter);
router.use('/prompts', promptHistoryRouter);
router.use(entityRoutes.path, entityRoutes.routes);
router.use(entityMethodRoutes.path, entityMethodRouter.routes);

export default router;
